export const DOMAIN_HEURISTICS: Record<string, string[]> = {
  security: [
    "attack",
    "injection",
    "vulnerability",
    "xss",
    "fuzzing",
    "auth",
    "jwt",
    "oauth",
    "security",
    "exploit",
    "encryption",
    "cybersecurity",
    "token",
    "password",
    "hash",
    "crypto",
  ],
  "code-review": [
    "code-review",
    "code review",
    "codereview",
    "requesting-code-review",
    "reviewer",
    "review-bot",
    "static-analysis",
    "quality-gate",
    "linter",
    "eslint",
    "prettier",
    "sonar",
  ],
  git: [
    "git",
    "github",
    "gitlab",
    "pull-request",
    "merge-request",
    "commit",
    "branch",
    "rebase",
    "cherry-pick",
    "release",
    "version-control",
    "svn",
    "bitbucket",
  ],
  "mobile-dev": [
    "mobile-development",
    "ios-development",
    "android-development",
    "react-native",
    "flutter",
    "swift",
    "kotlin",
    "capacitor",
    "xcode",
    "android-studio",
  ],
  "ai-ml": [
    "ai-",
    "ml-",
    "llm",
    "agent",
    "gpt",
    "claude",
    "gemini",
    "openai",
    "prompt",
    "rag",
    "machine-learning",
    "artificial-intelligence",
    "inference",
    "huggingface",
    "pytorch",
    "tensorflow",
  ],
  "web-dev": [
    "angular",
    "react",
    "vue",
    "tailwind",
    "frontend",
    "css",
    "html",
    "nextjs",
    "svelte",
    "astro",
    "web",
    "dom",
    "ui-patterns",
    "web-development",
    "webpack",
    "vite",
    "remix",
    "rollup",
    "esbuild",
  ],
  "backend-dev": [
    "api",
    "nestjs",
    "express",
    "django",
    "flask",
    "fastapi",
    "graphql",
    "rest",
    "grpc",
    "backend",
    "server",
    "backend-development",
    "microservices",
    "spring",
    "spring-boot",
    "ruby-on-rails",
    "laravel",
    "go",
    "golang",
  ],
  devops: [
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "ci-cd",
    "terraform",
    "ansible",
    "github-actions",
    "devops",
    "cloud",
    "deploy",
    "gcp",
    "jenkins",
    "gitlab-ci",
    "circleci",
    "prometheus",
    "grafana",
  ],
  database: [
    "sql",
    "mysql",
    "postgres",
    "mongo",
    "redis",
    "database",
    "schema",
    "prisma",
    "orm",
    "nosql",
    "sqlite",
    "mariadb",
    "cassandra",
    "dynamodb",
    "neo4j",
    "supabase",
    "drizzle",
    "typeorm",
  ],
  automation: [
    "automation",
    "zapier",
    "n8n",
    "selenium",
    "playwright",
    "puppeteer",
    "bot",
    "workflow",
    "scraper",
    "cypress",
    "cron",
    "puppet",
    "chef",
  ],
  design: [
    "design",
    "figma",
    "animation",
    "motion",
    "ux",
    "svg",
    "ui-design",
    "ui",
    "component",
    "styling",
    "css-in-js",
    "styled-components",
  ],
  programming: [
    "python",
    "javascript",
    "typescript",
    "java",
    "cpp",
    "ruby",
    "php",
    "csharp",
    "algorithm",
    "data-structure",
    "software-engineering",
    "software-development",
    "rust",
    "scala",
    "c",
    "c++",
  ],
  "data-engineering": [
    "bioinformatics",
    "data-analysis",
    "genomics",
    "data-science",
    "data-processing",
    "pandas",
    "spark",
    "hadoop",
    "airflow",
    "kafka",
    "dbt",
    "etl",
    "snowflake",
    "bigquery",
  ],
  productivity: [
    "productivity",
    "project-management",
    "workflow-automation",
    "documentation",
    "team-collaboration",
    "knowledge-management",
    "notion",
    "jira",
    "trello",
    "linear",
    "slack",
    "discord",
  ],
};

export function getCategoryForSkill(skillName: string): string {
  let exactMatch = false;
  let normalized = skillName.toLowerCase().replace(/_/g, "-");

  if (normalized.startsWith('"') && normalized.endsWith('"')) {
    exactMatch = true;
    normalized = normalized.slice(1, -1).trim().replace(/ /g, "-");
  }

  const hasPullRequestTerm = ["pr-review", "pull-request", "merge-request"].some((term) =>
    normalized.includes(term),
  );
  if (normalized.includes("review") && hasPullRequestTerm) {
    return "code-review";
  }

  for (const [category, keywords] of Object.entries(DOMAIN_HEURISTICS)) {
    if (exactMatch) {
      if (keywords.includes(normalized)) {
        return category;
      }
      continue;
    }

    if (keywords.some((keyword) => normalized.includes(keyword))) {
      return category;
    }
  }

  return "_uncategorized";
}
